### ISSUE TITLE
overrides does not work for pagination

### ISSUE THREAD

**Issue by hanweifish** [uber-web/baseui#380] opened 2018-10-12 17:56 UTC
try: overrides={{DropdownMenu: {style: {bottom: '10px'}}}}

seems like the overrides does not propagate styles to the very end node

**Comment by blackswanny** [comment] 2018-10-12 17:58
yes, I checked this case. Most popular way to override styles doesn't come through 
![image](https://user-images.githubusercontent.com/1851469/46885709-a13fa680-ce0d-11e8-9d50-6ae599f7e1cf.png)

It  stops propagating at menu stateful container 
![image](https://user-images.githubusercontent.com/1851469/46885738-b87e9400-ce0d-11e8-837b-5365b4891279.png)

**Comment by schnerd** [comment] 2018-10-12 18:21
Thanks for reporting this.

The issue is that `DropdownMenu` is not a styled component, it is another baseui component that we are re-using inside of Pagination. We're still figuring out the best way to support propagating style overrides into other baseui components re-used internally. See **Components Re-use & Overrides** in #375 for related discussion, and please share thoughts if you have any.

**Comment by abmai** [comment] 2018-10-12 19:31
Thanks for flagging this, @hanweifish!

@blackswanny what you pointed out is definitely a bug, but not the cause here. Specifically, in this case, it's not completely clear how to override the styles for this `DropdownMenu`. The API is overriding the top level `Menu` component but the styling needs to be applied to an internal styled component.

I'll throw up a fix for this that should get us to a working stage, but yes we need to re-evaluate the ways we're handling propagation of overrides for re-used Base UI components.

**Closed** 2018-10-29 20:51 UTC
