### ISSUE TITLE
Toast getting called twice under React.StrictMode

### ISSUE THREAD

**Issue by zifahm** [uber-web/baseui#1635] opened 2019-07-25 09:39 UTC
## Current Behavior
Toast getting called twice under React.StrictMode

https://codesandbox.io/s/toaster-basic-usage-ydc7f

## Expected Behavior
Toast should only be called once.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.11.0  |
| React   |  16.8.6       |
| browser |    chrome 75     |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by tajo** [comment] 2019-07-25 17:30
It intentionally invokes some methods twice: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects - we run some unexpected side-effect

we should consider using `StrictMode` for our docs site.

**Comment by rbrishabh** [comment] 2019-08-27 11:10
Hey! Can I take this up?

**Comment by chasestarr** [comment] 2019-09-06 18:03
closed the strict mode addition pr, but wanted to make sure this is no longer an issue. I can't reproduce the double toast described in the original post

https://deploy-preview-1844--baseui.netlify.com/components/toast/

**Comment by chasestarr** [comment] 2019-09-06 18:03
closing for now, but we can reopen if this is still a problem

**Closed by chasestarr** 2019-09-06 18:03 UTC
Labels: bug, good first issue
