### ISSUE TITLE
StatefulToggle checked prop doesn't change state of the toggle

### ISSUE THREAD

**Issue by jasonbarone** [uber-web/baseui#402] opened 2018-10-18 05:13 UTC
I'm trying to pass state into the StatefulToggle component's `checked` prop and it doesn't look like it will trigger state the way onChange does.

## Expected Behavior
Passing the `checked` prop via state should change state in the component similar to how the onChange method works.

## Current Behavior
Passing checked will not set state in the toggle.

## Steps to Reproduce
Pass a boolean into checked:
```
        <StatefulCheckbox
          checkmarkType="toggle"
          checked={this.state.toggleSidebarState}
          onChange={this.toggleSidebar}
        />
```

**Comment by nadiia** [comment] 2018-10-19 17:06
Hi @jasonbarone, thanks for filing the issue! In the example you provided it seems that `StatefulCheckbox` is used. In order to set the initial state for a stateful checkbox you'd need to pass it like this:
```
<StatefulCheckbox
          checkmarkType="toggle"
          initialState: {
             checked: true,
          },
          onChange={this.toggleSidebar}
        />
```
Further change of the `checked` prop will be controlled by the `StatefulCheckbox`'s internal state and cann't be updated based on a new value passed to the `initialState` prop during the same lifecycle. 
If you want to have more control over the `checked` state you'd need to use a controlled `Checkbox` component.
Please let me know if you have additional questions or issues. 
Will close this issue as it's not a bug.

**Comment by nadiia** [comment] 2018-10-19 17:15
@jasonbarone I noticed that you use a string value for the `checkmarkType` - it's recommended to import the `STYLE_TYPE` constant and use it as `checkmarkType: STYLE_TYPE.toggle`

**Closed** 2018-10-19 18:04 UTC
Labels: question

**Comment by jasonbarone** [comment] 2018-10-19 18:06
Thanks @nadiia, `Checkbox` is exactly what I needed.
