### ISSUE TITLE
[Controlled Input] Losing focus when Controlled Input has overrides for Input or InputContainer

### ISSUE THREAD

**Issue by zirho** [uber-web/baseui#321] opened 2018-09-28 19:45 UTC
Version 1.10.0

```
class TestingInput extends React.Component {
  state = {
    value: 'initial value',
  };

  render() {
    return (
      <ControlledInput
        placeholder="Controlled input"
        value={this.state.value}
        onChange={e => {
          const value = e.target.value;
          this.setState({value});
        }}
        overrides={{
          Input: withStyle(StyledInput, props => {
            return {width: 'auto'};
          }),
          InputContainer: withStyle(StyledInputContainer, props => {
            return {borderColor: '#276EF1'};
          }),
        }}
      />
    );
  }
}
```

When you render this component, it loses focus on every key press.
I think it's due to rendering a new component on every render in this code.
https://github.com/uber-web/baseui/blob/master/src/input/base-input.js#L102-L104

According to my investigation, it happens when either Input or InputContainer is provided to the ControlledInput.

**Comment by nadiia** [comment] 2018-10-10 19:32
@zirho You are correct, the issue is in the creating a new component on every render, but the root of it is in the code of the example above:
```
overrides={{
          Input: withStyle(StyledInput, props => {
            return {width: 'auto'};
          }),
          InputContainer: withStyle(StyledInputContainer, props => {
            return {borderColor: '#276EF1'};
          }),
}}
```
`withStyle` creates a new component here. In order to fix it you'll need to move the override component creating out of the `render`. Try this quick example:
```
class TestingInput extends React.Component {
  state = {
    value: 'initial value',
  };

  input = withStyle(StyledInput, props => {
    return {width: 'auto'};
  });

  inputContainer = withStyle(StyledInputContainer, props => {
    return {borderColor: '#276EF1'};
  });

  render() {
    return (
      <ControlledInput
        placeholder="Controlled input"
        value={this.state.value}
        onChange={e => {
          const value = e.target.value;
          this.setState({value});
        }}
        overrides={{
          Input: this.input,
          InputContainer: this.inputContainer,
        }}
      />
    );
  }
}
```

**Comment by nadiia** [comment] 2018-10-10 19:33
Closing the issue as it's not a component bug.

**Closed by nadiia** 2018-10-10 19:33 UTC

**Comment by zirho** [comment] 2018-10-16 18:42
Oh, thanks!
